# Generated by Django 2.0.2 on 2018-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180228_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
