# Generated by Django 2.0.2 on 2018-02-28 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodorder'),
        ('event', '0002_event_url'),
        ('user', '0005_attendee_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='event.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='food_orders',
            field=models.ManyToManyField(to='food.FoodOrder'),
        ),
    ]
