# Generated by Django 2.0.2 on 2018-02-28 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180228_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
    ]
