# Generated by Django 2.0.2 on 2018-03-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='BBQ', max_length=50)),
                ('event_date', models.DateField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_guests', models.IntegerField(default=0)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('food_orders', models.ManyToManyField(to='food.FoodOrder')),
            ],
            options={
                'db_table': 'event_attendees',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='event.EventAttendee', to='user.Attendee'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'event_date')},
        ),
    ]
