# Generated by Django 2.0.2 on 2018-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(default='BBQ', max_length=50)),
                ('event_date', models.DateField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
