# Generated by Django 2.0.2 on 2018-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='food_types',
            field=models.ManyToManyField(to='food.Food'),
        ),
    ]
